<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#1.-Import-packages" data-toc-modified-id="1.-Import-packages-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>1. Import packages</a></span></li><li><span><a href="#2.-set-parameters" data-toc-modified-id="2.-set-parameters-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>2. set parameters</a></span></li><li><span><a href="#3.-calculation" data-toc-modified-id="3.-calculation-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>3. calculation</a></span></li><li><span><a href="#4.solve-linear-program-maximizing-expected-profit" data-toc-modified-id="4.solve-linear-program-maximizing-expected-profit-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>4.solve linear program maximizing expected profit</a></span></li><li><span><a href="#5.-More-Computation-for-cost,-profit,-risk-and-sharpe" data-toc-modified-id="5.-More-Computation-for-cost,-profit,-risk-and-sharpe-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>5. More Computation for cost, profit, risk and sharpe</a></span><ul class="toc-item"><li><span><a href="#In-python-np.std-use-n-as-denominator-not-n-1,-matlab-std-use-n-1-that's-where-the-difference!" data-toc-modified-id="In-python-np.std-use-n-as-denominator-not-n-1,-matlab-std-use-n-1-that's-where-the-difference!-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>In python np.std use n as denominator not n-1, matlab std use n-1 that's where the difference!</a></span></li></ul></li><li><span><a href="#Here-we-should-use-n-as-denominator-because-the-variance-we-calculate-here-is-not-an-estimation" data-toc-modified-id="Here-we-should-use-n-as-denominator-because-the-variance-we-calculate-here-is-not-an-estimation-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Here we should use n as denominator because the variance we calculate here is not an estimation</a></span></li><li><span><a href="#Why-we-should-choose-only-stock?--[2.5000000e+03,-1.0383546e-07],-because-stock-has-a-higher-return-expected-rate" data-toc-modified-id="Why-we-should-choose-only-stock?--[2.5000000e+03,-1.0383546e-07],-because-stock-has-a-higher-return-expected-rate-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Why we should choose only stock?  [2.5000000e+03, 1.0383546e-07], because stock has a higher return expected rate</a></span></li></ul></div>

## 1. Import packages

In [1]:
import numpy as np
from scipy.optimize import linprog

## 2. set parameters

In [10]:
# Get Prices and future prices, each has 1/3 probability 
stock_price = 20
stock_prices_future = np.transpose(np.array([[40,20,12]]))
bond_price = 90
bond_prices_future = np.transpose(np.array([[100,100,100]]))

In [3]:
stock_prices_future

array([[40],
       [20],
       [12]])

## 3. calculation

In [4]:
# Get expected profits
expected_profit_stock = np.mean(stock_prices_future-stock_price)
expected_profit_bond = 10

# get returns for stock and bond
stock_returns = (stock_prices_future - stock_price)/stock_price;
bond_returns = (bond_prices_future - bond_price)/bond_price;

# expected returns for stock
expected_stock_return = np.mean(stock_returns)
expected_bond_return = np.mean(bond_returns)
print('expected_stock_return: ',expected_stock_return)
print('expected_bond_return: ',expected_bond_return)

expected_stock_return:  0.19999999999999998
expected_bond_return:  0.1111111111111111


## 4.solve linear program maximizing expected profit

In [5]:
# define the function to maximize
# why negative here? Because linprog is used to minimize
f = [-1*expected_profit_stock, -1*expected_profit_bond]
A = [[20, 90]]
b = [50000]
x0_bounds = (0, None)
x1_bounds = (0, None)
result = linprog(f, A_ub=A, b_ub=b, bounds=[x0_bounds, x1_bounds])

In [6]:
print(result)

     con: array([], dtype=float64)
     fun: -9999.999985319324
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([6.92499598e-05])
  status: 0
 success: True
       x: array([2.5000000e+03, 1.0383546e-07])


## 5. More Computation for cost, profit, risk and sharpe

In [7]:
# what is expected profit?
expected_profit =  -np.dot(np.array(f),np.array(result.x));
expected_profit

9999.999985319324

In [8]:
# compute cost of portfolio
cost = np.dot(np.array([stock_price,bond_price]), np.array(result.x))
print(cost)

49999.99993075004


In [19]:
stock_prices_future.reshape(3)

array([40, 20, 12])

In [20]:
np.transpose(np.array([stock_prices_future.reshape(3),np.squeeze(bond_prices_future)]))

array([[ 40, 100],
       [ 20, 100],
       [ 12, 100]])

In [11]:
np.squeeze(bond_prices_future)

array([100, 100, 100])

In [21]:
# computation of Risk
 
portfolio_prices_future = np.dot(np.transpose(np.array([stock_prices_future.reshape(3),np.squeeze(bond_prices_future)])), np.array(result.x))
print('portfolio_prices_future:  ',portfolio_prices_future)

portfolio_returns = (portfolio_prices_future- cost)/cost
print('portfolio_returns:  ',portfolio_returns)

portfolio_prices_future:   [99999.99985319 49999.99993179 29999.99996323]
portfolio_returns:   [ 1.00000000e+00  2.07671838e-11 -4.00000000e-01]


### In python np.std use n as denominator not n-1, matlab std use n-1 that's where the difference! 

In [22]:
# In python np.std use n as denominator not n-1, matlab std use n-1 that's where the difference! 
mu = np.mean(portfolio_returns)
sigma = np.std(portfolio_returns)
 
# calculate sharpe!
sharpe = mu/sigma
print('sharpe', sharpe)

sharpe 0.33968311027865006


## Here we should use n as denominator because the variance we calculate here is not an estimation

In [23]:
np.sqrt(np.sum((portfolio_returns-mu)**2/3))

0.5887840576451439

In [24]:
sigma

0.5887840576451439

## Why we should choose only stock?  [2.5000000e+03, 1.0383546e-07], because stock has a higher return expected rate